### ISSUE TITLE
Json acceptor double vs single quotes

### ISSUE THREAD

**Issue by paulmaksimovich** [otriscon/llm-structured-output#1]
Is there anything that can be done to encourage valid json quote choices?

For example, I am using the hermes-2-pro model with a pydantic json prompt, and also doing this structured output using the same schema.

I get invalid outputs like:
```
{"questions": ["What are some common varieties of apples that have different colors and flavors?', 'How do
```

The structured generation will switch from enclosing with double quotes, to enclosing with single quotes.
It happens more often if the text is `trying to 'quote' something`.
Any tips?

**Comment by otriscon** [comment]
A couple of things come to mind:
- What temperature are you using? Try temp=0 (i.e. sampling the highest probability token).
- Try to help the model focus on producing valid json by ending the prompt with the start of a JSON code block, e.g.:
```
You're a helpful assistant etc...
Given the following paragraph, extract questions into a valid JSON object according to this JSON schema:
${schema}
Output:
```json
```

There are ways to reduce (or even zero out) the probability of selecting the single quote tokens, but this may remove valid outputs when the input does contain the single quote. In my experience, when the model is getting JSON quotes wrong, it means it's struggling to complete the task, and changing the prompt to be more precise helps.

If you don't mind sharing an example prompt that fails this way, I'll be happy to debug it on my system.

**Comment by paulmaksimovich** [comment]
I've tinkered a bit more and you are completely right.
I've been able to get a variety of reliable results.
When it goes astray it does seem to be an indication that there is something problematic with the prompt.
Great job, thanks!
