### ISSUE TITLE
Model insisting on selecting a not-very-useful tool even if given an alternative

### ISSUE THREAD

**Issue by uogbuji** [otriscon/llm-structured-output#6]
Hi @otriscon this ticket is probably as much as anything an attempt to cash in in your [offer of close collab to really follow the workings of llm-structured-output](https://github.com/otriscon/llm-structured-output/pull/5#issuecomment-2248544335). 😂

In [Toolio](https://github.com/OoriData/Toolio) I'm trying to give the tool-caller an "out" so that it can optionally call provided functions, but that doesn't seem to be working in a way that makes me think something about the sampling is really pushing for a selection of a possibly unhelpful function. Hopefully this self-contained script illustrates the problem: https://gist.github.com/uogbuji/78ddddf9bf8e72dd44c5626321db681c

Most of it is just code copied from the examples dir here, but look at the prompt set up, and notice that it **always** insists on calling `today_kfabe`. I've tried with several LLMs; same result. Any thoughts?

**Comment by uogbuji** [comment]
Oh BTW, if we do find a way to collab, we can also discuss incorporating [MLX's newly-landed prompt caching](https://x.com/awnihannun/status/1829289495210099012) 😊

**Comment by otriscon** [comment]
Hi @uogbuji,

I looked at the gist and can't see anything obviously wrong with the schema, but the prompt doesn't seem totally coherent: there is a `sysprompt` where the LLM is instructed to behave as a writing assistant, which is not consistent with the user `prompt` below it. The user prompt itself is written in the style of a system prompt, and there's no actual user input that I can see in the gist. This may have been a copy/paste issue when moving the code to the gist?

Regarding prompt caching, looks cool. I'll have a look and see if I can come up with an example to use it with `llm-structured-output`.

**Comment by uogbuji** [comment]
You're right, I had spent most of yesterday puzzling through a far more complex scenario, which I thought I'd boiled down to behavior in the underlying sampler. I thought it would be easy to assemble a fully packaged reproduction case, but it wasn't, and I ended up copying some of the wrong things in 😅. I've fixed the gist in place.

Continuing with that fixed script, and also thinking with a clearer head again this morning, I do think my problem is 2-part 1) Getting the prompting right 2) Limitations of the LLMs. It's probably not on the llm-structured-output side, but you may be amused by my findings, anyway. Results from the updated gist:

With Hermes-2-Theta-Llama-3:

```py
{'choices': [{'index': 0, 'message': {'role': 'assistant', 'tool_calls': [{'id': 'call_17584599056_1725025191_0', 'type': 'function', 'function': {'name': 'today_kfabe', 'arguments': '{}'}}, {'id': 'call_17584599056_1725025191_1', 'type': 'function', 'function': {'name': 'toolio_none', 'arguments': '{"response": "Artificial minds, like the sun\\nRise and set, but never done\\nIntelligence won"}'}}]}, 'finish_reason': 'tool_calls'}], 'usage': {'completion_tokens': 55, 'prompt_tokens': 296, 'total_tokens': 351}, 'object': 'chat.completion', 'id': 'chatcmpl-17584599056_1725025191', 'created': 1725025191, 'model': 'mlx-community/Hermes-2-Theta-Llama-3-8B-4bit'}
```

So insists on calling both functions, even though `toolio_none` alone should be the obvious preference.

With Mistral-Nemo-Instruct:

```py
{'choices': [{'index': 0, 'message': {'role': 'assistant', 'tool_calls': [{'id': 'call_17479857872_1725025744_0', 'type': 'function', 'function': {'name': 'today_kfabe', 'arguments': '{}'}}]}, 'finish_reason': 'tool_calls'}], 'usage': {'completion_tokens': 16, 'prompt_tokens': 289, 'total_tokens': 305}, 'object': 'chat.completion', 'id': 'chatcmpl-17479857872_1725025744', 'created': 1725025744, 'model': 'mlx-community/Mistral-Nemo-Instruct-2407-4bit'}
```

Calls the dummy function and not even `toolio_none` at all, which is very disappointing for a model I'd found extremely capable in the past.

With Arcee-Agent:

```py
{'choices': [{'index': 0, 'message': {'role': 'assistant', 'tool_calls': [{'id': 'call_26102185232_1725026029_0', 'type': 'function', 'function': {'name': 'toolio_none', 'arguments': '{"response": "In the digital realm,\\nAI weaves its poetic spell,\\nHaiku born of code."}'}}]}, 'finish_reason': 'tool_calls'}], 'usage': {'completion_tokens': 47, 'prompt_tokens': 295, 'total_tokens': 342}, 'object': 'chat.completion', 'id': 'chatcmpl-26102185232_1725026029', 'created': 1725026029, 'model': 'mlx-community/Arcee-Agent-8bit'}
```

Seems to nail the case, which makes sense, because this is a model specifically fine-tuned for tool-calling. Still funny to see all 3 possibilities from the first 3 separate I re-tested models. I'll probably have to step up my game in testing scenario performance across models for Toolio users. And I'll also have to fix whatever is garbling the prompting in the fuller case.

So I'll close this, and sorry for the noise, but let me also say that I'd still love to take you up on that explainer, if you happen to have the time, sometime!

**Comment by otriscon** [comment]
Thanks @uogbuji for the details on output on several LLMs, very interesting.

I do have time to go through structured output. I see you're on the MLX discord, I'll ping you there.

**Comment by uogbuji** [comment]
Yup. I'm `CodeGriot`!
